//
// Generated By:JAX-WS RI 2.2.10 (JAXB RI IBM IBM 2.2.10-05/18/2015 1:33:48 PMjviswana-)
//


package com.tcs.libertysample.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "helloworld", namespace = "http://libertysample.tcs.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "helloworld", namespace = "http://libertysample.tcs.com/")
public class Helloworld {


}
