//
// Generated By:JAX-WS RI 2.2.10 (JAXB RI IBM IBM 2.2.10-05/18/2015 1:33:48 PMjviswana-)
//


package com.tcs.libertysample.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "helloworldResponse", namespace = "http://libertysample.tcs.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "helloworldResponse", namespace = "http://libertysample.tcs.com/")
public class HelloworldResponse {

    @XmlElement(name = "return", namespace = "")
    private String _return;

    /**
     * 
     * @return
     *     returns String
     */
    public String getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(String _return) {
        this._return = _return;
    }

}
